/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package org.scalacheck.engine

import org.junit.platform.engine.discovery.DiscoverySelectors.selectClass
import org.junit.platform.testkit.engine.EngineTestKit
import org.junit.runner.RunWith
import org.scalatest.FunSuite
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class ScalaCheckIntegrationTests extends FunSuite {
  test("can execute Properties subclass") {
    EngineTestKit.engine(new ScalaCheckEngine)
      .selectors(selectClass(StringSpecification.getClass))
      .execute()
      .containerEvents()
      .debug()
      .assertStatistics(stats => stats.started(2))
  }
}
